### ISSUE TITLE
docker-compose 启动配置

### ISSUE THREAD

**Issue by feix** [cmcmsec/dpia#16]
启动 `sudo docker-compose -f docker-compose.yml up -d`

dpia.sql 开头增加 
`CREATE DATABASE dpia;  use dpia;`

修改 dpia/settngs.py  中 DATABASES 配置为 
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dpia',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'dpia_mysql',
        'PORT': '3306',
    }
}
```

其他依赖文件

docker-compose.yml
```yml
version: '3.3'

services:
  app_python:
    container_name: dpia
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db_mysql
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  db_mysql:
    image: mysql:latest
    container_name: dpia_mysql
    ports:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
    volumes:
      - "./dpia.sql:/docker-entrypoint-initdb.d/dpia.sql"
```

Dockerfile
```shell
FROM python:3.8.5

WORKDIR /dpia
COPY requirements.txt /dpia/
RUN pip install --no-cache-dir -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
COPY . /dpia/

CMD [ "bash", "entry.sh"]
```

entry.sh
```shell
python manage.py migrate
python manage.py init_data
python manage.py crontab_task_gen
python manage.py crontab_permission_verify
python manage.py runserver 0.0.0.0:$PORT
```

requirements.txt
```
############
# DATABASE #
############
pymysql==0.10.1

#########
# UTILS #
#########
python-dateutil==2.6.1
gevent==1.4.0
cerberus==1.3.2
concurrent-log-handler==0.9.17
arrow==0.15.4

##########
# DJANGO #
##########
django<3,>2.2
django-environ==0.4.5
django-filter==2.3.0
django-braces==1.14.0
djangorestframework==3.11.1
mysqlclient
django-mysql
```
